# Generated by Django 4.1 on 2022-08-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("List", "0002_rename_person_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("COMPLETE", "Complete"), ("INCOMPLETE", "Incomplete")],
                default="Incomplete",
                max_length=10,
            ),
        ),
    ]
